application: even-cirrus-178212
version: 1-alpha
runtime: python27
api_version: 1
threadsafe: yes

handlers:
 - url: /static
   static_dir: static/
   application_readable: true
   expiration: 1d
 - url: .*
   script: main_site.wsgi.application

libraries:
 - name: MySQLdb
   version: 1.2.5
 - name: PIL
   version: 1.1.7

skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
